server:
  port: 8080


spring:
  application:
    name: lyric
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lyric?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
